day10/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path
from django.urls.conf import include
from django.views.generic.base import TemplateView

from member import views as member_views
from post import views as post_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # post
    path('', post_views.PostListView.as_view(), name='main'),
    path('create/', post_views.PostCreateView.as_view(), name='create'),
    path('<int:pk>/update/', post_views.PostUpdateView.as_view(), name='update'),
    # like
    path('like/', post_views.toggle_like, name='toggle_like'),
    # auth
    path('signup/', member_views.SignupView.as_view(), name='signup'),
    # path('signup/done/', TemplateView.as_view(template_name='auth/signup_done.html'), name='signup_done'),
    path('verify/', member_views.verify_email, name='verify_email'),
    path('login/', member_views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # include
    path('comment/', include('post.comment_urls')),
    path('profile/', include('member.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

day10/member/urls.py
from django.urls.conf import path
from . import views

app_name = 'profile'

urlpatterns = [
    path('<str:slug>/', views.UserProfileView.as_view(), name='detail'),
    path('<int:pk>/follow/', views.UserFollowingView.as_view(), name='follow'),
]

day10/post/models.py
import re

from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import post_save
from django.dispatch.dispatcher import receiver

from utils.models import TimeStampModel

User = get_user_model()

class Post(TimeStampModel):
    content = models.TextField('본문')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'[{self.user}] post'

    class Meta:
        verbose_name = '포스트'
        verbose_name_plural = '포스트 목록'


class PostImage(TimeStampModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField('이미지', upload_to='post/%Y-%m-%d')

    def __str__(self):
        return f'{self.post} image'

    class Meta:
        verbose_name = '이미지'
        verbose_name_plural = '이미지 목록'


class Tag(TimeStampModel):
    tag = models.CharField('태그', max_length=100)
    posts = models.ManyToManyField(Post, related_name='tags')

    def __str__(self):
        return self.tag


class Comment(TimeStampModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField('내용',max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'[comment] {self.post} | {self.user}'


class Like(TimeStampModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes')

    def __str__(self):
        return f'[like] {self.post} | {self.user}'


@receiver(post_save, sender=Post)
def post_post_save(sender, instance, created, **kwargs):
    hashtags = re.findall(r'#(\w{1,100})(?=\s|$)', instance.content)

    instance.tags.clear()  # 중계 모델 삭제

    if hashtags:
        tags = [
            Tag.objects.get_or_create(tag=hashtag)
            for hashtag in hashtags
        ]
        # tags = [
        #     [Tag, True],
        #     [Tag, False],
        # ]
        # 이런식으로 저장됨

        tags = [ tag for tag, _ in tags ]   # 저 중에 Tag 객체만 남김

        instance.tags.add(*tags)

day10/templates/profile/detail.html
{% extends 'base.html' %}
{% load humanize %}
{% block style %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
    <style>
    .post-image{
        aspect-ratio : 1 / 1;
        object-fit : cover;
    }
    .add-comment:hover{
    background-color : black !important;
    color : white !important;
    }
    </style>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-10 offset-1 col-lg-6 offset-lg-3">
            <div>
                <span class="p-2 border rounded-circle me-2">
                    <i class="fa-solid fa-user" style="width:16px; padding-left:3px;"></i>
                </span>
                {{ object.nickname }}
                {% if object != request.user  %}
                    <form action="{% url 'profile:follow' object.pk %}" method="post" class="d-inline">
                        {% csrf_token %}
                        <button class="btn btn-primary btn-sm ms-3">
                            {% if is_follow %}
                                Unfollow
                            {% else %}
                                Follow
                            {% endif %}
                        </button>
                    </form>
                {% endif %}
            </div>

            <div class="row mt-3">
                <div class="col-4 text-center">{{ object.post_set.count | intcomma }} posts</div>
                <div class="col-4 text-center">{{ object.followers.count | intcomma }} followers</div>
                <div class="col-4 text-center">{{ object.followings.count | intcomma }} following</div>
            </div>

            <div class="row mt-3">
                {% for post in object.post_set.all %}
                    <div class="col-4">
                        <div class="swiper">
                            <div class="border-1 swiper-wrapper">
                                {% for post_image in post.images.all %}
                                    <div class="swiper-slide">
                                        <img class="img-fluid post-image" src="{{ post_image.image.url }}" alt="">
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="swiper-pagination"></div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <script>
        const swiper = new Swiper('.swiper', {
          // Optional parameters
          direction: 'horizontal',
          loop: false,

          // If we need pagination
          pagination: {
            el: '.swiper-pagination',
          },
        });
        let infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            offset: 'bottom-in-view',
            onAfterPageLoad: function ($items){
                $items.find('.swiper').each(function(){
                    new Swiper(this, {
                        pagination: {el:$(this).find('.swiper-pagination')[0]}
                });
            });
        }
        })
    </script>
{% endblock %}