day7/blog/urls.py
from xml.etree.ElementInclude import include
from django.urls import path

from blog import cb_views
from blog import views

app_name = 'blog'

urlpatterns = [
    # CBV blog
    path('', cb_views.BlogListView.as_view(), name='list'),
    path('<int:blog_pk>/', cb_views.BlogDetailView.as_view(), name='detail'),
    path('create/', cb_views.BlogCreateView.as_view(), name='create'),
    path('<int:pk>/update', cb_views.BlogUpdateView.as_view(), name='update'),
    # path('<int:pk>/update', views.blog_update, name='update'),
    path('<int:pk>/delete', cb_views.BlogDeleteView.as_view(), name='delete'),

    path('comment/create/<int:blog_pk>', cb_views.CommentCreateView.as_view(), name='comment_create'),
]

day7/config/urls.py
from django.contrib import admin
from django.shortcuts import redirect, render
from django.urls import path, include
from django.views.generic.base import TemplateView, RedirectView, View
from django.conf import settings
from django.conf.urls.static import static

from blog import views, cb_views
from config.settings import LOGIN_REDIRECT_URL
from member import views as member_views

# class AboutView(TemplateView):
#     template_name = 'about.html'
#
# class TestView(View) :
#     def get(self, request):
urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('blog.urls')),
    path('fb/', include('blog.fbv_urls')),

    # auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', member_views.sign_up, name='signup'),
    path('login/', member_views.login, name='login'),

    # # path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    # path('about/', AboutView.as_view(), name='about'),
    # path('redirect/', RedirectView.as_view(pattern_name='about'), name='redirect'),
    # # path('redirect2/', lambda req : redirect('about')),
    # path('test/', TestView.as_view(), name='test'),

    # summernote
    path('summernote/', include('django_summernote.urls')),
]


if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

day7/blog/models.py
from io import BytesIO
from pathlib import Path

from PIL import Image
from django.contrib.auth import get_user_model
from django.db import models

from utils.models import TimestampModel

User = get_user_model()

class Blog(TimestampModel):
    CATEGORY_CHOICES = (
    ('free', '자유'),
    ('travel', '여행'),
    ('cat', '고양이'),
    ('dog', '강아지'),
    )

    category = models.CharField('카테고리', max_length=10, choices=CATEGORY_CHOICES, default='free')
    title = models.CharField('제목', max_length=100)
    content = models.TextField('본문')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    image = models.ImageField('이미지', null=True, blank=True, upload_to='blog/%Y-%m-%d')
    thumbnail = models.ImageField('썸네일', null=True, blank=True, upload_to='blog/%Y-%m-%d/thumbnail')
    # models.CASCADE => 같이 삭제
    # models.PROTECT => 삭제 불가능 (유저를 삭제하려고 할 때 블로그가 있으면 삭제 불가능)
    # models.SET_NULL => 블로그의 author가 NULL이 됨

    def __str__(self):
        return f"[{self.get_category_display()}] {self.title[:10]}"

    def get_absolute_url(self):
        from django.urls.base import reverse
        return reverse('blog:detail', kwargs={'blog_pk': self.pk})

    def get_thumbnail_image_url(self):
        if self.thumbnail:
            return self.thumbnail.url
        elif self.image:
            return self.image.url
        return None

    def save(self, *args, **kwargs):
        if not self.image :
            return super().save(*args, **kwargs)

        image = Image.open(self.image)
        image.thumbnail((300, 300))

        image_path = Path(self.image.name)

        thumbnail_name = image_path.stem    # blog/2025-07-41/database.png => database만 가져옴
        thumbnail_extension = image_path.suffix.lower() # blog/2025-07-41/database.png => .png만 가져옴
        thumbnail_filename = f"{thumbnail_name}_thumb{thumbnail_extension}" # databse_thumb.png

        if thumbnail_extension in ['.jpg', '.jpeg'] :
            file_type = 'JPEG'
        elif thumbnail_extension == '.gif' :
            file_type = 'GIF'
        elif thumbnail_extension == '.png' :
            file_type = 'PNG'
        else :
            return super().save(*args, **kwargs)

        temp_thumb = BytesIO()
        image.save(temp_thumb, file_type)
        temp_thumb.seek(0)

        self.thumbnail.save(thumbnail_filename, temp_thumb, save=False)
        temp_thumb.close()
        return super().save(*args, **kwargs)


    class Meta:
        verbose_name = '블로그'
        verbose_name_plural = '블로그 목록'


class Comment(TimestampModel):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    content = models.CharField('본문', max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.blog.title} 댓글'

    class Meta:
        verbose_name = '댓글'
        verbose_name_plural = '댓글 목록'
        ordering = ['-created_at', '-id']

day7/blog/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget

from blog.models import Blog, Comment


class BlogForm(forms.ModelForm) :
    class Meta:
        model = Blog
        fields = ('category', 'title', 'image', 'content')
        widgets = {
            'content' : SummernoteWidget()
        }
        


class CommentForm(forms.ModelForm) :
    class Meta:
        model = Comment
        fields = ('content',)
        widgets = {
            'content' : forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'content' : '댓글'
        }

day7/blog/views.py
from django.core.paginator import Paginator
from django.http.response import Http404
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.views.decorators.http import require_http_methods

from blog.forms import BlogForm
from blog.models import Blog


def blog_list(request):
    blogs = Blog.objects.all().order_by('-created_at')

    q = request.GET.get('q')
    if q :
        blogs = blogs.filter(
            Q(title__icontains=q) |
            Q(content__icontains=q)
        )
        # blogs = blogs.filter(content__icontains=q)

    paginator = Paginator(blogs, 10)
    page = request.GET.get('page')  # 현재 페이지 넘버 가져옴
    page_object = paginator.get_page(page)

    # visits = int(request.COOKIES.get('visit', 0)) + 1    # visit키의 값을 가져오고, 존재하지 않으면 0을 가져옴
    # request.session['count'] = request.session.get('count', 0) + 1

    context = {
        # 'blogs': blogs,
        # 'count' : request.session['count']
        'object_list': page_object.object_list,
        'page_obj': page_object,
    }

    response = render(request, 'blog_list.html', context)
    # response.set_cookie('visit', visits)
    return response


def blog_detail(request, pk) :
    blog = get_object_or_404(Blog, pk=pk)
    context = {'blog': blog}
    return render(request, 'blog_detail.html', context)


@login_required
def blog_create(request):
    # if not request.user.is_authenticated():
    #     return redirect(reverse('login'))
    form = BlogForm(request.POST or None)
    if form.is_valid() :
        blog = form.save(commit=False)
        blog.author = request.user
        blog.save()
        return redirect(reverse('fb:detail',kwargs={'pk':blog.pk}))

    context = {'form' : form}
    return render(request, template_name='blog_form.html', context=context)


@login_required
def blog_update(request, pk):
    if request.user.is_superuser :
        blog = get_object_or_404(Blog, pk=pk)
    else :
        blog = get_object_or_404(Blog, pk=pk, author=request.user)
    # if request.user != blog.author:
    #     raise Http404

    form = BlogForm(request.POST or None, request.FILES or None,instance=blog)
    if form.is_valid() :
        blog = form.save()
        return redirect(reverse('fb:detail',kwargs={'pk':blog.pk}))

    context = {
        'blog': blog,
        'form' : form,
    }
    return render(request, template_name='blog_form.html', context=context)


@login_required
@require_http_methods(['POST'])
def blog_delete(request, pk):
    # if request.method != "POST":
    #     raise Http404
    blog = get_object_or_404(Blog, pk=pk, author=request.user)
    blog.delete()

    return redirect(reverse('fb:list'))

day7/templates/blog_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="mt-2 d-flex justify-content-between">
        <h1>{{ blog.title }}</h1>

        {% if request.user == blog.author or request.user.is_staff %}
        <div>
            <a class="btn btn-sm btn-warning" href="{% url 'blog:update' blog.pk %}">수정</a>

            <form id='delete_form' action="{% url 'blog:delete' blog.pk%}" method="POST" style="display:inline">
                {% csrf_token %}
                <button type="button" id="delete_btn" class="btn btn-sm btn-danger">삭제</button>
            </form>
        </div>
        {% endif %}
    </div>

    <div style="text-align:right">
        {{ blog.author.username }}
    </div>
    <hr>
    {% if blog.image %}
        <img src="{{ blog.image.url }}" alt="" class="w-100">
    {% endif %}
    <p>{{ blog.content | safe }}</p>
    <hr>

    {% if request.user.is_authenticated %}
        <form method="POST" action="{% url 'blog:comment_create' blog.pk %}">
            {% csrf_token %}
            {{ comment_form.as_p }}
        <div class="text-end">
            <button class="btn btn-sm btn-primary">작성</button>
        </div>
        </form>

        <hr>
    {% endif %}

    <div class="mb-2" id="comment_wrapper">
        {% for comment in object_list %}
            <div class="border-bottom">{{ comment.content }}
                <p class="text-end">
                    <small>{{ comment.created_at | date:'Y-m-d H:i' }} | {{ comment.author.username }}</small>
                </p>
            </div>
        {% endfor %}
    </div>

    {% include 'pagination.html' with fragment='comment_wrapper'%}

    <a class="btn btn-sm btn-info" href="{% url 'blog:list' %}">목록</a>
{% endblock %}

{% block js %}
    <script>
        document.querySelector('#delete_btn').addEventListener('click', function() {
            if(confirm('삭제하시겠습니까?')){
                document.querySelector('#delete_form').submit();
            }
        })
    </script>
{% endblock %}

day7/templates/blog_form.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="mt-2">블로그 {{ sub_title }}</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary">
            {% if btn_name %}
                {{ btn_name }}
            {% else %}
                저장
            {% endif %}
        </button>
    </form>
{% endblock %}

{% block js %}
    {% include 'form-js.html' %}
{% endblock %}

day7/templates/blog_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="mt-2">
        <h1 class="d-inline">블로그 목록</h1>
        <a href="{% url 'blog:create' %}" class="float-end btn btn-sm btn-primary">생성</a>
    </div>

    <hr>

    {% for blog in object_list %}
        <div class="my-1">
            <a href="{% url 'blog:detail' blog.pk %}" class="link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover row">
                {% if blog.get_thumbnail_image_url %}
                    <img src="{{ blog.get_thumbnail_image_url }}" alt="" class="col-2">
                {% endif %}
{#                {% if blog.thumbnail %}#}
{#                    <img src="{{ blog.thumbnail.url }}" alt="" class="col-2">#}
{#                {% elif blog.image %}#}
{#                    <img src="{{ blog.image.url }}" alt="" class="col-2">#}
{#                {% endif %}#}
                <span class="col-10">
                    [{{ blog.get_category_display }}] {{ blog.title }} <span>({{ blog.author.username }})</span>- <small>{{ blog.created_at | date:"Y-m-d"}}</small>
                </span>
            </a>
        </div>
    {% endfor %}

    <form method="GET" class="my-3 d-flex">
        <input class="form-control-sm" name="q" type="text" placeholder="검색어를 입력하세요." value="{% if request.GET.q %}{{ request.GET.q }}{% endif %}">
        <button class="btn btn-sm btn-info ms-2">검색</button>
    </form>

    {% include 'pagination.html' %}
{% endblock %}